/*
 * Created on 23 Jun 2017 ( Time 11:23:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
