package com.gvpt.admintool.web.common.enumerations;

public enum UserActivity {
	LOGIN,
	LOGOUT,
	SAVE_ACCES_ROLE,
	UPDATE_ACCES_ROLE,
	DELETE_ACCES_ROLE,
	SAVE_USER_MANAGEMENT,
	UPDATE_USER_MANAGEMENT,
	DELETE_USER_MANAGEMENT,
	SAVE_THRESHOLD,
	UPDATE_THRESHOLD,
	DELETE_THRESHOLD,
	SAVE_USER_NOTIFICATION,
	UPDATE_USER_NOTIFICATION,
	DELETE_USER_NOTIFICATION,
	SEND_EMAIL,
	SEND_SMS,
	SAVE_TRACKING_CONFIG,
	UPDATE_TRACKING_CONFIG;
}
