/*
 * Created on 20 Jun 2017 ( Time 13:11:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gvpt.admintool.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "GVPT_ACCESS_RIGHT"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="GVPT_ACCESS_RIGHT")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessRightEntity.countAll", query="SELECT COUNT(x) FROM AccessRightEntity x" )
} )
public class AccessRightEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ACCESS_RIGHT_ID", nullable=false)
    private Long       accessRightId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAME", nullable=false, length=100)
    private String     name         ;

    @Column(name="DESCRIPTION", length=500)
    private String     description  ;

    @Column(name="STATUS", nullable=false)
    private Long       status       ;

    @Column(name="CREATED_BY", nullable=false)
    private String       createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false)
    private Date       createdDate  ;

    @Column(name="MODIFIED_BY")
    private String       modifiedBy   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE")
    private Date       modifiedDate ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToMany(mappedBy="listOfAccessRight", targetEntity=AccessRoleEntity.class, fetch=FetchType.LAZY)
    private List<AccessRoleEntity> listOfAccessRole;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessRightEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAccessRightId( Long accessRightId ) {
        this.accessRightId = accessRightId ;
    }
    public Long getAccessRightId() {
        return this.accessRightId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NAME ( VARCHAR2 ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR2 ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : STATUS ( NUMBER ) 
    public void setStatus( Long status ) {
        this.status = status;
    }
    public Long getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : CREATED_BY ( NUMBER ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : CREATED_DATE ( DATE ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : MODIFIED_BY ( NUMBER ) 
    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    //--- DATABASE MAPPING : MODIFIED_DATE ( DATE ) 
    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfAccessRole( List<AccessRoleEntity> listOfAccessRole ) {
        this.listOfAccessRole = listOfAccessRole;
    }
    public List<AccessRoleEntity> getListOfAccessRole() {
        return this.listOfAccessRole;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(accessRightId);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedDate);
        return sb.toString(); 
    } 

}
