/*
 * Created on 10 Jul 2017 ( Time 09:58:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gvpt.admintool.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "GVPT_ACCESS_ROLE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="GVPT_ACCESS_ROLE")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessRoleEntity.countAll", query="SELECT COUNT(x) FROM AccessRoleEntity x" )
} )
public class AccessRoleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ACCESS_ROLE_ID", nullable=false)
    private Long       accessRoleId ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ROLE_TITLE", nullable=false, length=100)
    private String     roleTitle    ;

    @Column(name="CREATED_BY", nullable=false)
    private String       createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false)
    private Date       createdDate  ;

    @Column(name="MODIFIED_BY")
    private String       modifiedBy   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE")
    private Date       modifiedDate ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    @ManyToMany(targetEntity=AccessRightEntity.class, fetch=FetchType.LAZY)
    @JoinTable(name="GVPT_USER_ROLE_RIGHTS", 
      joinColumns=@JoinColumn(name="ACCESS_ROLE_ID", referencedColumnName="ACCESS_ROLE_ID"),
      inverseJoinColumns=@JoinColumn(name="ACCESS_RIGHT_ID", referencedColumnName="ACCESS_RIGHT_ID")
     ) 
    private List<AccessRightEntity> listOfAccessRight;

    @OneToMany(mappedBy="accessRole", targetEntity=UserAdminEntity.class, fetch=FetchType.LAZY)
    private List<UserAdminEntity> listOfUserAdmin;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessRoleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAccessRoleId( Long accessRoleId ) {
        this.accessRoleId = accessRoleId ;
    }
    public Long getAccessRoleId() {
        return this.accessRoleId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ROLE_TITLE ( VARCHAR2 ) 
    public void setRoleTitle( String roleTitle ) {
        this.roleTitle = roleTitle;
    }
    public String getRoleTitle() {
        return this.roleTitle;
    }

    //--- DATABASE MAPPING : CREATED_BY ( NUMBER ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : CREATED_DATE ( DATE ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : MODIFIED_BY ( NUMBER ) 
    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    //--- DATABASE MAPPING : MODIFIED_DATE ( DATE ) 
    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUserAdmin( List<UserAdminEntity> listOfUserAdmin ) {
        this.listOfUserAdmin = listOfUserAdmin;
    }
    public List<UserAdminEntity> getListOfUserAdmin() {
        return this.listOfUserAdmin;
    }

    public void setListOfAccessRight( List<AccessRightEntity> listOfAccessRight ) {
        this.listOfAccessRight = listOfAccessRight;
    }
    public List<AccessRightEntity> getListOfAccessRight() {
        return this.listOfAccessRight;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(accessRoleId);
        sb.append("]:"); 
        sb.append(roleTitle);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedDate);
        return sb.toString(); 
    } 

}
