/*
 * Created on 20 Jun 2017 ( Time 13:11:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gvpt.admintool.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "GVPT_AUDIT_TRAIL"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="GVPT_AUDIT_TRAIL")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AuditTrailEntity.countAll", query="SELECT COUNT(x) FROM AuditTrailEntity x" )
} )
public class AuditTrailEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="AUDIT_TRAIL_ID", nullable=false)
    private Long       auditTrailId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="USER_ID", nullable=false)
    private String       userId       ;

    @Column(name="ACTION", nullable=false, length=100)
    private String     action       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTION_DATETIME", nullable=false)
    private Date       actionDatetime ;

    @Column(name="REFERENCE")
    private String     references   ;

    @Column(name="IP_ADDRESS", length=16)
    private String     ipAddress    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AuditTrailEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAuditTrailId( Long auditTrailId ) {
        this.auditTrailId = auditTrailId ;
    }
    public Long getAuditTrailId() {
        return this.auditTrailId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : USER_ID ( NUMBER ) 
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : ACTION ( VARCHAR2 ) 
    public void setAction( String action ) {
        this.action = action;
    }
    public String getAction() {
        return this.action;
    }

    //--- DATABASE MAPPING : ACTION_DATETIME ( DATE ) 
    public void setActionDatetime( Date actionDatetime ) {
        this.actionDatetime = actionDatetime;
    }
    public Date getActionDatetime() {
        return this.actionDatetime;
    }

    //--- DATABASE MAPPING : REFERENCES ( NCLOB ) 
    public void setReferences( String references ) {
        this.references = references;
    }
    public String getReferences() {
        return this.references;
    }

    //--- DATABASE MAPPING : IP_ADDRESS ( VARCHAR2 ) 
    public void setIpAddress( String ipAddress ) {
        this.ipAddress = ipAddress;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(auditTrailId);
        sb.append("]:"); 
        sb.append(userId);
        sb.append("|");
        sb.append(action);
        sb.append("|");
        sb.append(actionDatetime);
        sb.append("|");
        sb.append(references);
        sb.append("|");
        sb.append(ipAddress);
        return sb.toString(); 
    } 

}
