/*
 * Created on 20 Jun 2017 ( Time 10:17:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service.mapping;

import org.modelmapper.Condition;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.modelmapper.spi.MappingContext;
import org.springframework.stereotype.Component;

import com.gvpt.admintool.bean.AccessRole;
import com.gvpt.admintool.bean.jpa.AccessRoleEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccessRoleServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccessRoleServiceMapper() {
		Condition timeslot = new Condition() {
			   @Override
			   public boolean applies(MappingContext context) {
			    return 
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfGvptUserNotification");
			   }
			  };
			  modelMapper = new ModelMapper();
			  modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT).setPropertyCondition(timeslot);
	}

	/**
	 * Mapping from 'AccessRoleEntity' to 'AccessRole'
	 * @param accessRoleEntity
	 */
	public AccessRole mapAccessRoleEntityToAccessRole(AccessRoleEntity accessRoleEntity) {
		if(accessRoleEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AccessRole accessRole = map(accessRoleEntity, AccessRole.class);

		return accessRole;
	}
	
	/**
	 * Mapping from 'AccessRole' to 'AccessRoleEntity'
	 * @param accessRole
	 * @param accessRoleEntity
	 */
	public void mapAccessRoleToAccessRoleEntity(AccessRole accessRole, AccessRoleEntity accessRoleEntity) {
		if(accessRole == null) {
			return;
		}

		//--- Generic mapping 
		map(accessRole, accessRoleEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}