/*
 * Created on 20 Jun 2017 ( Time 10:18:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service.mapping;

import org.modelmapper.Condition;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.modelmapper.spi.MappingContext;
import org.springframework.stereotype.Component;

import com.gvpt.admintool.bean.AccessRight;
import com.gvpt.admintool.bean.jpa.AccessRightEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccessRightServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccessRightServiceMapper() {
		Condition timeslot = new Condition() {
			   @Override
			   public boolean applies(MappingContext context) {
			    return 
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfUserAdmin");
			   }
			  };
			  modelMapper = new ModelMapper();
			  modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT).setPropertyCondition(timeslot);
	}

	/**
	 * Mapping from 'AccessRightEntity' to 'AccessRight'
	 * @param accessRightEntity
	 */
	public AccessRight mapAccessRightEntityToAccessRight(AccessRightEntity accessRightEntity) {
		if(accessRightEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AccessRight accessRight = map(accessRightEntity, AccessRight.class);

		return accessRight;
	}
	
	/**
	 * Mapping from 'AccessRight' to 'AccessRightEntity'
	 * @param accessRight
	 * @param accessRightEntity
	 */
	public void mapAccessRightToAccessRightEntity(AccessRight accessRight, AccessRightEntity accessRightEntity) {
		if(accessRight == null) {
			return;
		}

		//--- Generic mapping 
		map(accessRight, accessRightEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}