/*
 * Created on 20 Jun 2017 ( Time 10:17:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.gvpt.admintool.bean.AuditTrail;
import com.gvpt.admintool.bean.jpa.AuditTrailEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AuditTrailServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AuditTrailServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AuditTrailEntity' to 'AuditTrail'
	 * @param auditTrailEntity
	 */
	public AuditTrail mapAuditTrailEntityToAuditTrail(AuditTrailEntity auditTrailEntity) {
		if(auditTrailEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AuditTrail auditTrail = map(auditTrailEntity, AuditTrail.class);

		return auditTrail;
	}
	
	/**
	 * Mapping from 'AuditTrail' to 'AuditTrailEntity'
	 * @param auditTrail
	 * @param auditTrailEntity
	 */
	public void mapAuditTrailToAuditTrailEntity(AuditTrail auditTrail, AuditTrailEntity auditTrailEntity) {
		if(auditTrail == null) {
			return;
		}

		//--- Generic mapping 
		map(auditTrail, auditTrailEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}