/*
 * Created on 20 Jun 2017 ( Time 16:55:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service.mapping;

import org.modelmapper.Condition;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.modelmapper.spi.MappingContext;
import org.springframework.stereotype.Component;

import com.gvpt.admintool.bean.UserAdmin;
import com.gvpt.admintool.bean.jpa.UserAdminEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserAdminServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserAdminServiceMapper() {
		Condition timeslot = new Condition() {
			   @Override
			   public boolean applies(MappingContext context) {
			    return 
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfUserAdmin") &&
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfAccessRight");
			   }
			  };
			  modelMapper = new ModelMapper();
			  modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT).setPropertyCondition(timeslot);
	}

	/**
	 * Mapping from 'UserAdminEntity' to 'UserAdmin'
	 * @param userAdminEntity
	 */
	public UserAdmin mapUserAdminEntityToUserAdmin(UserAdminEntity userAdminEntity) {
		if(userAdminEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UserAdmin userAdmin = map(userAdminEntity, UserAdmin.class);

		return userAdmin;
	}
	
	/**
	 * Mapping from 'UserAdmin' to 'UserAdminEntity'
	 * @param userAdmin
	 * @param userAdminEntity
	 */
	public void mapUserAdminToUserAdminEntity(UserAdmin userAdmin, UserAdminEntity userAdminEntity) {
		if(userAdmin == null) {
			return;
		}

		//--- Generic mapping 
		map(userAdmin, userAdminEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}