/*
 * Created on 20 Jun 2017 ( Time 10:17:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service.mapping;

import org.modelmapper.Condition;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.modelmapper.spi.MappingContext;
import org.springframework.stereotype.Component;

import com.gvpt.admintool.bean.UserAdmin;
import com.gvpt.admintool.bean.jpa.UserAdminEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserServiceMapper() {
		Condition timeslot = new Condition() {
			   @Override
			   public boolean applies(MappingContext context) {
			    return 
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfUserAdmin") &&
			    		!context.getMapping().getLastDestinationProperty().getName().equals("listOfAccessRight");
			   }
			  };
			  modelMapper = new ModelMapper();
			  modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT).setPropertyCondition(timeslot);
	}

	/**
	 * Mapping from 'UserEntity' to 'User'
	 * @param userEntity
	 */
	public UserAdmin mapUserEntityToUser(UserAdminEntity userEntity) {
		if(userEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UserAdmin user = map(userEntity, UserAdmin.class);

		return user;
	}
	
	/**
	 * Mapping from 'User' to 'UserEntity'
	 * @param user
	 * @param userEntity
	 */
	public void mapUserToUserEntity(UserAdmin user, UserAdminEntity userEntity) {
		if(user == null) {
			return;
		}

		//--- Generic mapping 
		map(user, userEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}