/*
 * Created on 20 Jun 2017 ( Time 10:19:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum AccessRightIndexEnum {

    ACCESSRIGHTID (0) {
		@Override
        public String toString() {
            return "accessRightId";
        }
	}, 	
    NAME (1) {
		@Override
        public String toString() {
            return "name";
        }
	}, 	
    DESCRIPTION (2) {
		@Override
        public String toString() {
            return "description";
        }
	}, 	
    STATUS (3) {
		@Override
        public String toString() {
            return "status";
        }
	}, 	
    CREATEDBY (4) {
		@Override
        public String toString() {
            return "createdBy";
        }
	}, 	
    CREATEDDATE (5) {
		@Override
        public String toString() {
            return "createdDate";
        }
	}, 	
    MODIFIEDBY (6) {
		@Override
        public String toString() {
            return "modifiedBy";
        }
	}, 	
    MODIFIEDDATE (7) {
		@Override
        public String toString() {
            return "modifiedDate";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private AccessRightIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(AccessRightIndexEnum e : AccessRightIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}