/*
 * Created on 20 Jun 2017 ( Time 10:16:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum AccessRoleIndexEnum {

    ACCESSROLEID (0) {
		@Override
        public String toString() {
            return "accessRoleId";
        }
	}, 	
    ROLETITLE (1) {
		@Override
        public String toString() {
            return "roleTitle";
        }
	}, 	
    CREATEDBY (2) {
		@Override
        public String toString() {
            return "createdBy";
        }
	}, 	
    CREATEDDATE (3) {
		@Override
        public String toString() {
            return "createdDate";
        }
	}, 	
    MODIFIEDBY (4) {
		@Override
        public String toString() {
            return "modifiedBy";
        }
	}, 	
    MODIFIEDDATE (5) {
		@Override
        public String toString() {
            return "modifiedDate";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private AccessRoleIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(AccessRoleIndexEnum e : AccessRoleIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}