/*
 * Created on 20 Jun 2017 ( Time 10:16:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum AuditTrailIndexEnum {

    AUDITTRAILID (0) {
		@Override
        public String toString() {
            return "auditTrailId";
        }
	}, 	
    USERID (1) {
		@Override
        public String toString() {
            return "userId";
        }
	}, 	
    ACTION (2) {
		@Override
        public String toString() {
            return "action";
        }
	}, 	
    ACTIONDATETIME (3) {
		@Override
        public String toString() {
            return "actionDatetime";
        }
	}, 	
    REFERENCES (4) {
		@Override
        public String toString() {
            return "references";
        }
	}, 	
    IPADDRESS (5) {
		@Override
        public String toString() {
            return "ipAddress";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private AuditTrailIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(AuditTrailIndexEnum e : AuditTrailIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}