/*
 * Created on 20 Jun 2017 ( Time 16:54:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum CodeConfigIndexEnum {

    CODECONFIGID (0) {
		@Override
        public String toString() {
            return "codeConfigId";
        }
	}, 	
    CODETYPE (1) {
		@Override
        public String toString() {
            return "codeType";
        }
	}, 	
    CODENAME (2) {
		@Override
        public String toString() {
            return "codeName";
        }
	}, 	
    CODEVALUE (3) {
		@Override
        public String toString() {
            return "codeValue";
        }
	}, 	
    STATUS (4) {
		@Override
        public String toString() {
            return "status";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private CodeConfigIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(CodeConfigIndexEnum e : CodeConfigIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}