/*
 * Created on 20 Jun 2017 ( Time 10:16:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum UserIndexEnum {

    USERID (0) {
		@Override
        public String toString() {
            return "userId";
        }
	}, 	
    FIRSTNAME (1) {
		@Override
        public String toString() {
            return "firstName";
        }
	}, 	
    LASTNAME (2) {
		@Override
        public String toString() {
            return "lastName";
        }
	}, 	
    EMAIL (3) {
		@Override
        public String toString() {
            return "email";
        }
	}, 	
    PASSWORD (4) {
		@Override
        public String toString() {
            return "password";
        }
	}, 	
    CONTACTNUMBER (5) {
		@Override
        public String toString() {
            return "contactNumber";
        }
	}, 	
    STATUS (6) {
		@Override
        public String toString() {
            return "status";
        }
	}, 	
    CREATEDBY (7) {
		@Override
        public String toString() {
            return "createdBy";
        }
	}, 	
    CREATEDDATE (8) {
		@Override
        public String toString() {
            return "createdDate";
        }
	}, 	
    MODIFIEDBY (9) {
		@Override
        public String toString() {
            return "modifiedBy";
        }
	}, 	
    MODIFIEDDATE (10) {
		@Override
        public String toString() {
            return "modifiedDate";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private UserIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(UserIndexEnum e : UserIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}