/*
 * Created on 20 Jun 2017 ( Time 16:54:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum UserAdminIndexEnum {
	
	DEFAULT (0) {
		@Override
        public String toString() {
            return "userId";
        }
	}, 
    USERID (1) {
		@Override
        public String toString() {
            return "userId";
        }
	}, 	
    NAME (2) {
		@Override
        public String toString() {
            return "name";
        }
	}, 	
    ROLE (3) {
		@Override
        public String toString() {
            return "accessRole.roleTitle";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private UserAdminIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(UserAdminIndexEnum e : UserAdminIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}