/*
 * Created on 20 Jun 2017 ( Time 10:16:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.datatable.enumerations;

import java.util.HashMap;
import java.util.Map;

public enum UserRoleRightsIndexEnum {

    ACCESSROLEID (0) {
		@Override
        public String toString() {
            return "accessRoleId";
        }
	}, 	
    ACCESSRIGHTID (1) {
		@Override
        public String toString() {
            return "accessRightId";
        }
	}; 	

	private int val;
	private static final Map<Integer, String> maps = new HashMap<Integer, String>();
	
	private UserRoleRightsIndexEnum(int val) {
		this.val = val;
	}

	public static Map<Integer, String> getMaps() {
		for(UserRoleRightsIndexEnum e : UserRoleRightsIndexEnum.values()){
			maps.put(e.val, e.toString());
		}
		return maps;
	}

	public int getVal() {
		return val;
	}
	
}