/*
 * Created on 20 Jun 2017 ( Time 10:16:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service;

import java.util.List;

import org.springframework.data.domain.Pageable;

import com.gvpt.admintool.bean.AccessRole;
import com.gvpt.admintool.data.repository.specifications.AccessRoleSpecifications;
/**
 * Business Service Interface for entity AccessRole.
 */
public interface AccessRoleService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param accessRoleId
	 * @return entity
	 */
	AccessRole findById( Long accessRoleId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AccessRole> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AccessRole save(AccessRole entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccessRole update(AccessRole entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccessRole create(AccessRole entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param accessRoleId
	 */
	void delete( Long accessRoleId );

	Long countAll();
	List<AccessRole> findAll(Pageable pageable);
	List<AccessRole> findWithSpec(AccessRoleSpecifications specifications, Pageable pageable);
	Long countWithSpec(AccessRoleSpecifications specifications);
}
