/*
 * Created on 20 Jun 2017 ( Time 10:19:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service;

import java.util.List;

import org.springframework.data.domain.Pageable;

import com.gvpt.admintool.bean.AccessRight;
import com.gvpt.admintool.data.repository.specifications.AccessRightSpecifications;
/**
 * Business Service Interface for entity AccessRight.
 */
public interface AccessRightService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param accessRightId
	 * @return entity
	 */
	AccessRight findById( Long accessRightId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AccessRight> findAll();
	
	List<AccessRight> findAllOrderById();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AccessRight save(AccessRight entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccessRight update(AccessRight entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccessRight create(AccessRight entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param accessRightId
	 */
	void delete( Long accessRightId );

	Long countAll();
	List<AccessRight> findAll(Pageable pageable);
	List<AccessRight> findWithSpec(AccessRightSpecifications specifications, Pageable pageable);
	Long countWithSpec(AccessRightSpecifications specifications);
}
