/*
 * Created on 20 Jun 2017 ( Time 10:16:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service;

import java.util.Date;
import java.util.List;

import org.springframework.data.domain.Pageable;

import com.gvpt.admintool.bean.AuditTrail;
import com.gvpt.admintool.data.repository.specifications.AuditTrailSpecifications;
/**
 * Business Service Interface for entity AuditTrail.
 */
public interface AuditTrailService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param auditTrailId
	 * @return entity
	 */
	AuditTrail findById( Long auditTrailId  ) ;
	
	AuditTrail findLastLoginById( String idUser  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AuditTrail> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AuditTrail save(AuditTrail entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AuditTrail update(AuditTrail entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AuditTrail create(AuditTrail entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param auditTrailId
	 */
	void delete( Long auditTrailId );

	Long countAll();
	List<AuditTrail> findAll(Pageable pageable);
	List<AuditTrail> findWithSpec(AuditTrailSpecifications specifications, Pageable pageable);
	Long countWithSpec(AuditTrailSpecifications specifications);
	AuditTrail saveAudit(String userId, Enum<?> activity, Date actionDateTime, String references, String ipAddress);
}
