/*
 * Created on 7 Oct 2017 ( Time 18:41:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service;

import java.util.List;
import org.springframework.data.domain.Pageable;

import com.gvpt.admintool.bean.CodeConfig;
import com.gvpt.admintool.data.repository.specifications.CodeConfigSpecifications;
/**
 * Business Service Interface for entity CodeConfig.
 */
public interface CodeConfigService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param codeConfigId
	 * @param codeType
	 * @param codeName
	 * @return entity
	 */
	CodeConfig findById( Long codeConfigId, String codeType, String codeName  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CodeConfig> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CodeConfig save(CodeConfig entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CodeConfig update(CodeConfig entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CodeConfig create(CodeConfig entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param codeConfigId
	 * @param codeType
	 * @param codeName
	 */
	void delete( Long codeConfigId, String codeType, String codeName );

	Long countAll();
	List<CodeConfig> findAll(Pageable pageable);
	List<CodeConfig> findWithSpec(CodeConfigSpecifications specifications, Pageable pageable);
	Long countWithSpec(CodeConfigSpecifications specifications);
}
