/*
 * Created on 20 Jun 2017 ( Time 11:34:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.gvpt.admintool.business.service;

import java.math.BigDecimal;


/**
 * Login Interface.
 * 
 * @author Telosys Tools Generator by cxrus
 *
 */
public interface LoginService {
	void logout(BigDecimal id);
	boolean changePassword(String email, String newPassword);
	boolean resetPassword(String email, String newPassword);
	boolean checkFirstLogin(String email);
	boolean checkPasswordById(String email, String password);
	
	

	
}
