/*
 * Created on 20 Jun 2017 ( Time 16:54:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.business.service;

import java.util.List;

import org.springframework.data.domain.Pageable;

import com.gvpt.admintool.bean.UserAdmin;
import com.gvpt.admintool.data.repository.specifications.UserAdminSpecifications;
/**
 * Business Service Interface for entity UserAdmin.
 */
public interface UserAdminService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userId
	 * @return entity
	 */
	UserAdmin findById( String userId  ) ;
	
	UserAdmin findOneByIDandStatus(String userId,Long status) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserAdmin> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserAdmin save(UserAdmin entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserAdmin update(UserAdmin entity);
	
	UserAdmin updateStatus(UserAdmin entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserAdmin create(UserAdmin entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userId
	 */
	void delete( String userId );

	Long countAll();
	List<UserAdmin> findAll(Pageable pageable);
	List<UserAdmin> findWithSpec(UserAdminSpecifications specifications, Pageable pageable);
	Long countWithSpec(UserAdminSpecifications specifications);

	UserAdmin getUserByEmail(String email);
	UserAdmin getUserByID(String id);
}
