/*
 * Created on 4 Jul 2017 ( Time 14:21:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.listitem;

import com.gvpt.admintool.bean.AccessRight;
import com.gvpt.admintool.web.common.ListItem;

public class AccessRightListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public AccessRightListItem(AccessRight accessRight) {
		super();

		this.value = ""
			 + accessRight.getAccessRightId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = accessRight.getName();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
