/*
 * Created on 20 Jun 2017 ( Time 10:40:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.listitem;

public class AccessRightListItemTemporary{
private String id;
private String name;
private boolean check;

private String idforUI;

public String getId() {
	return id;
}

public void setId(String id) {
	this.id = id;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public boolean getCheck() {
	return check;
}

public void setCheck(boolean check) {
	this.check = check;
}

public String getIdforUI() {
	return idforUI;
}

public void setIdforUI(String idforUI) {
	this.idforUI = idforUI;
}


}
