/*
 * Created on 4 Jul 2017 ( Time 14:21:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.listitem;

import com.gvpt.admintool.bean.AccessRight;
import com.gvpt.admintool.web.common.ListItem;

import java.io.Serializable;

public class ChildMenuListItem implements ListItem, Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final String value ;
	private final String label ;
	
	public ChildMenuListItem(String value, String label) {
		super();
		this.value = value;
		this.label = label;
	}

	public ChildMenuListItem(AccessRight accessRight) {
		super();

		this.value = ""
			 + accessRight.getAccessRightId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = accessRight.getName();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
