/*
 * Created on 20 Jun 2017 ( Time 10:40:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.web.listitem;

import com.gvpt.admintool.bean.UserAdmin;
import com.gvpt.admintool.web.common.ListItem;

public class UserListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UserListItem(UserAdmin user) {
		super();

		this.value = ""
			 + user.getUserId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = user.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
