/*
 * Created on 20 Jun 2017 ( Time 11:34:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.gvpt.admintool.bean.auth;

import java.io.Serializable;
import java.math.BigDecimal;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Generated By Telosys
 * Property of CXRUS Solutions
 * 
 * @author zuniawan.andiprastia
 *
 */
public class ChangePassword implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5377288385862527108L;
	
	private BigDecimal userId;
	
	@NotEmpty
	private String currentPassword;
	
	@NotEmpty
	private String newPassword;
	
	@NotEmpty
	private String retypeNewPassword;
	
	public String getCurrentPassword() {
		return currentPassword;
	}
	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}
	public String getNewPassword() {
		return newPassword;
	}
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
	public String getRetypeNewPassword() {
		return retypeNewPassword;
	}
	public void setRetypeNewPassword(String retypeNewPassword) {
		this.retypeNewPassword = retypeNewPassword;
	}
	public BigDecimal getUserId() {
		return userId;
	}
	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}
	
	
}
