/*
 * Created on 20 Jun 2017 ( Time 11:34:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.gvpt.admintool.bean.auth;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Generated by Telosys
 * property of Cxrus Solutions
 * 
 * @author zuniawan.andiprastia
 *
 */
public class ResetPassword {
	
	private String email;
	
	private String oldPassword;
	
	@NotEmpty
	private String newPassword;
	
	@NotEmpty
	private String retypeNewPassword;
	
	@NotEmpty
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getNewPassword() {
		return newPassword;
	}
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
	public String getRetypeNewPassword() {
		return retypeNewPassword;
	}
	public void setRetypeNewPassword(String retypeNewPassword) {
		this.retypeNewPassword = retypeNewPassword;
	}
	public String getOldPassword() {
		return oldPassword;
	}
	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}
	
	
	
}
