/*
 * Created on 10 Jul 2017 ( Time 09:58:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Java bean for 'AccessRole' entity
 * 
 * @author Telosys Tools
 *
 */
public class AccessRole implements Serializable {

    private static final long serialVersionUID = 1L;

    @Transient
    private int no;
    
    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : ACCESS_ROLE_ID NUMBER 
    private Long accessRoleId;
    
    

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Pattern(regexp = "[a-zA-Z\\s]+",message = "User Role Must Be Letters")
    @NotNull
    private String roleTitle;

    // DB : CREATED_BY NUMBER 
    private String createdBy;

    // DB : CREATED_DATE DATE 
    private Date createdDate;

    // DB : MODIFIED_BY NUMBER 
    private String modifiedBy;

    // DB : MODIFIED_DATE DATE 
    private Date modifiedDate;
    
    @Transient
    private boolean use =false;
    @JsonIgnore
    private List<UserAdmin> listOfUserAdmin=new ArrayList<UserAdmin>();
    @JsonIgnore
    private List<AccessRight> listOfAccessRight=new ArrayList<AccessRight>();
    



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAccessRoleId( Long accessRoleId ) {
        this.accessRoleId = accessRoleId ;
    }

    public Long getAccessRoleId() {
        return this.accessRoleId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRoleTitle( String roleTitle ) {
        this.roleTitle = roleTitle;
    }
    public String getRoleTitle() {
        return this.roleTitle;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
      

	public List<UserAdmin> getListOfUserAdmin() {
		return listOfUserAdmin;
	}

	public void setListOfUserAdmin(List<UserAdmin> listOfUserAdmin) {
		this.listOfUserAdmin = listOfUserAdmin;
	}

	public List<AccessRight> getListOfAccessRight() {
		return listOfAccessRight;
	}

	public void setListOfAccessRight(List<AccessRight> listOfAccessRight) {
		this.listOfAccessRight = listOfAccessRight;
	}
	
	

	public boolean isUse() {
		return use;
	}

	public void setUse(boolean use) {
		this.use = use;
	}
	
	

	public Integer getNo() {
		return no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("\naccessRoleId:");
        sb.append(accessRoleId);
        sb.append("\nroleTitle:");
        sb.append(roleTitle);
        sb.append("\ncreatedBy:");
        sb.append(createdBy);
        sb.append("\ncreatedDate:");
        sb.append(createdDate);
        sb.append("\nmodifiedBy:");
        sb.append(modifiedBy);
        sb.append("\nmodifiedDate:");
        sb.append(modifiedDate);
        return sb.toString(); 
    } 


}
