/*
 * Created on 20 Jun 2017 ( Time 13:08:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class AuditTrail implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long auditTrailId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private String userId;

    @NotNull
    @Size( min = 1, max = 100 )
    private String action;

    @NotNull
    private Date actionDatetime;

    @Size( max = 4000 )
    private String references;

    @Size( max = 16 )
    private String ipAddress;

    public AuditTrail(){}

    public AuditTrail(String userId, String action, Date actionDatetime,
			String references, String ipAddress) {
		super();
		this.userId = userId;
		this.action = action;
		this.actionDatetime = actionDatetime;
		this.references = references;
		this.ipAddress = ipAddress;
	}

	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAuditTrailId( Long auditTrailId ) {
        this.auditTrailId = auditTrailId ;
    }

    public Long getAuditTrailId() {
        return this.auditTrailId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setAction( String action ) {
        this.action = action;
    }
    public String getAction() {
        return this.action;
    }

    public void setActionDatetime( Date actionDatetime ) {
        this.actionDatetime = actionDatetime;
    }
    public Date getActionDatetime() {
        return this.actionDatetime;
    }

    public void setReferences( String references ) {
        this.references = references;
    }
    public String getReferences() {
        return this.references;
    }

    public void setIpAddress( String ipAddress ) {
        this.ipAddress = ipAddress;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("\nauditTrailId=");
        sb.append(auditTrailId);
        sb.append("\nuserId=");
        sb.append(userId);
        sb.append("\naction=");
        sb.append(action);
        sb.append("\nactionDatetime=");
        sb.append(actionDatetime);
        sb.append("\nreferences=");
        sb.append(references);
        sb.append("\nipAddress=");
        sb.append(ipAddress);
        return sb.toString(); 
    } 


}
