/*
 * Created on 7 Oct 2017 ( Time 18:41:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.bean;

import java.io.Serializable;


/**
 * Java bean for 'CodeConfig' entity
 * 
 * @author Telosys Tools
 *
 */
public class CodeConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : CODE_CONFIG_ID NUMBER 
    private Long codeConfigId;
    // DB : CODE_TYPE VARCHAR2 
    private String codeType;
    // DB : CODE_NAME VARCHAR2 
    private String codeName;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : CODE_VALUE VARCHAR2 
    private String codeValue;

    // DB : STATUS NUMBER 
    private Long status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodeConfigId( Long codeConfigId ) {
        this.codeConfigId = codeConfigId ;
    }

    public Long getCodeConfigId() {
        return this.codeConfigId;
    }

    public void setCodeType( String codeType ) {
        this.codeType = codeType ;
    }

    public String getCodeType() {
        return this.codeType;
    }

    public void setCodeName( String codeName ) {
        this.codeName = codeName ;
    }

    public String getCodeName() {
        return this.codeName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCodeValue( String codeValue ) {
        this.codeValue = codeValue;
    }
    public String getCodeValue() {
        return this.codeValue;
    }

    public void setStatus( Long status ) {
        this.status = status;
    }
    public Long getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codeConfigId);
        sb.append("|");
        sb.append(codeType);
        sb.append("|");
        sb.append(codeName);
        sb.append("|");
        sb.append(codeValue);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
