/*
 * Created on 10 Jul 2017 ( Time 09:58:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gvpt.admintool.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Java bean for 'UserAdmin' entity
 * 
 * @author Telosys Tools
 *
 */
public class UserAdmin implements Serializable {

    private static final long serialVersionUID = 1L;

    @Transient
    private int no;
    
    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : USER_ID NUMBER 
    @NotNull
    @Size( min = 1, max = 100 )
    private String       userId       ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String name;

    // DB : EMAIL VARCHAR2 
//    @NotNull
    @Size( min = 1, max = 100 )
    @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$", message="Your email is not valid")
    private String email;

    // DB : PASSWORD VARCHAR2 
    @Size( min = 8, max = 100 )
//    @Pattern(regexp = "^.*(?=.{8,})(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).*$")
    private String password;

    // DB : CONTACT_NUMBER VARCHAR2 
//    @NotNull
    @Size( min = 1, max = 20 )
//    @Pattern(regexp="(^$|[0-9]{10})", message="Your contact number is invalid")
    private String contactNumber;

    // DB : STATUS NUMBER 
    private Long status;

    // DB : CREATED_BY NUMBER 
    private String createdBy;

    // DB : CREATED_DATE DATE 
    private Date createdDate;

    // DB : MODIFIED_BY NUMBER 
    private String modifiedBy;

    // DB : MODIFIED_DATE DATE 
    private Date modifiedDate;

    private AccessRole accessRole;
    
    private boolean active;
    
    @NotNull
    private Long accessRoleId;
    
    @Transient
    private int rowForUi=0;
    
    @Transient
    private boolean check=false;
 
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserId( String userId ) {
        this.userId = userId ;
    }

	public String getUserId() {
        return this.userId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
   
    public boolean isActive() {
		return status == 1l ? true : false;
	}

	public void setEmail( String email ) {
        this.email = email;
    }
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
        return this.email;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setContactNumber( String contactNumber ) {
        this.contactNumber = contactNumber;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }

    public void setStatus( Long status ) {
        this.status = status;
    }
    public Long getStatus() {
        return this.status;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

  


    public AccessRole getAccessRole() {
		return accessRole;
	}

	public void setAccessRole(AccessRole accessRole) {
		this.accessRole = accessRole;
	}
	
	public Long getAccessRoleId() {
		return accessRoleId;
	}

	public void setAccessRoleId(Long accessRoleId) {
		this.accessRoleId = accessRoleId;
	}
	


	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("\nuserId:");
        sb.append(userId);
        sb.append("\nname:");
        sb.append(name);
        sb.append("\nemail:");
        sb.append(email);
        sb.append("\ncontactNumber:");
        sb.append(contactNumber);
        sb.append("\nstatus:");
        sb.append(status);
        sb.append("\ncreatedBy:");
        sb.append(createdBy);
        sb.append("\ncreatedDate:");
        sb.append(createdDate);
        sb.append("\nmodifiedBy:");
        sb.append(modifiedBy);
        sb.append("\nmodifiedDate:");
        sb.append(modifiedDate);
        return sb.toString(); 
    }

	public int getRowForUi() {
		return rowForUi;
	}

	public void setRowForUi(int rowForUi) {
		this.rowForUi = rowForUi;
	}

	public boolean isCheck() {
		return check;
	}

	public void setCheck(boolean check) {
		this.check = check;
	}

	public int getNo() {
		return no;
	}

	public void setNo(int no) {
		this.no = no;
	} 

	

}
